'use client';
import{FormEvent,useCallback,useEffect,useState}from'react';
import{allowedPairTransitions,PairState}from'../../lib/workflow';

type Stats={leads:number;converted:number;activePairs:number;approvedPairs:number;approvalRate:number|null;approvedRevenueCents:number;contributionCents:number;availableCredentials:number;reservedCredentials:number;launchTarget:number;launchProgress:number;pipeline:{state:string;count:number}[];milestones:{label:string;target:number;unlocked:boolean}[]};
type Pair={id:string;publicCode:string;state:PairState;campaign:{slug:string;name:string}|null;members:{role:string;name:string;email:string}[];credential:{label:string;status:string;releasedAt:string|null}|null};
type CredentialData={campaigns:{id:string;slug:string;name:string}[];bundles:{id:string;campaign_id:string;label:string;status:string;accounts:{slot:string;username:string}[]}[]};
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
const financial=new Set(['APPROVED','PAYABLE','PAID','PAYMENT_FAILED']);

export default function Admin(){
 const[stats,setStats]=useState<Stats|null>(null),[pairs,setPairs]=useState<Pair[]>([]),[credentials,setCredentials]=useState<CredentialData>({campaigns:[],bundles:[]}),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const load=useCallback(async()=>{setError('');try{const[rs,rp,rc]=await Promise.all([fetch('/api/admin/stats'),fetch('/api/admin/pairs'),fetch('/api/admin/credentials')]);const[ss,pp,cc]=await Promise.all([rs.json(),rp.json(),rc.json()]);if(!rs.ok||!rp.ok||!rc.ok)throw new Error(ss.error||pp.error||cc.error||'Unable to load admin');setStats(ss);setPairs(pp.pairs||[]);setCredentials(cc)}catch(e:any){setError(e.message)}},[]);
 useEffect(()=>{load()},[load]);
 async function post(url:string,body:any,key:string){setBusy(key);setError('');try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Action failed');await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function addCredential(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await post('/api/admin/credentials',{campaignSlug:f.get('campaignSlug'),label:f.get('label'),aUsername:f.get('aUsername'),aPassword:f.get('aPassword'),bUsername:f.get('bUsername'),bPassword:f.get('bPassword'),pairInvitationCode:f.get('pairInvitationCode'),notes:f.get('notes')},'credential-create');e.currentTarget.reset()}
 if(!stats&&!error)return <main className="admin"><p>Loading live operations…</p></main>;
 return <main className="admin admin-shell">
  <header className="admin-head"><div><div className="logo">PAIR<span>VOICE</span> <small>OPS</small></div><p className="eyebrow">APPROVED REVENUE FIRST</p><h1>Mission Control</h1><p className="admin-sub">Professional operations with just enough progress mechanics to keep the team moving. No vanity metrics.</p></div><div className="health-pill">● Live admin</div></header>
  {error&&<p className="error">{error}</p>}
  {stats&&<><section className="mission-card"><div><span className="kicker">LAUNCH MISSION</span><h2>{stats.approvedPairs} / {stats.launchTarget} approved pairs</h2><p>Prove quality and contribution before scaling acquisition.</p></div><strong>{stats.launchProgress}%</strong><div className="meter mission-meter"><i style={{width:stats.launchProgress+'%'}}/></div></section><section className="kpi-grid"><article><span>Approved revenue</span><b>{money(stats.approvedRevenueCents)}</b></article><article><span>Contribution</span><b>{money(stats.contributionCents)}</b></article><article><span>Approval rate</span><b>{stats.approvalRate==null?'—':stats.approvalRate+'%'}</b></article><article><span>Credential capacity</span><b>{stats.availableCredentials}</b><small>{stats.reservedCredentials} committed</small></article><article><span>Active pairs</span><b>{stats.activePairs}</b></article><article><span>Lead pool</span><b>{stats.leads}</b><small>{stats.converted} converted</small></article></section></>}

  <section className="admin-grid">
   <div className="panel"><span className="kicker">OPERATIONS QUEUE</span><h2>Pairs</h2><div className="ops-list">{pairs.length?pairs.map(p=><article className="ops-row" key={p.id}><div><strong>{p.publicCode}</strong><span>{p.campaign?.name||'Campaign'} · {p.members.map(m=>m.role+': '+m.name).join(' / ')||'Waiting for participant'}</span><small>{p.credential?'Credentials '+p.credential.label+' · '+p.credential.status:'No credentials reserved'}</small></div><div className="ops-actions"><b>{p.state.replaceAll('_',' ')}</b>{p.state==='READY'&&!p.credential&&<button disabled={busy!==''} onClick={()=>post('/api/admin/credentials/assign',{pairId:p.id},'assign-'+p.id)}>Reserve credentials</button>}{p.state==='READY'&&p.credential?.status==='RESERVED'&&<button disabled={busy!==''} onClick={()=>post('/api/admin/credentials/release',{pairId:p.id},'release-'+p.id)}>Release & start</button>}<select defaultValue="" onChange={e=>{const to=e.target.value as PairState;if(!to)return;const reason=window.prompt('Reason for this state change?');if(reason)post('/api/admin/pairs/transition',{pairId:p.id,toState:to,reason},'transition-'+p.id);e.currentTarget.value=''}}><option value="">Move state…</option>{allowedPairTransitions[p.state].filter(x=>!financial.has(x)).map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></div></article>):<p>No pairs yet.</p>}</div></div>
   <div className="panel"><span className="kicker">MILESTONES</span><h2>Operating badges</h2><div className="badge-row">{stats?.milestones.map(m=><div className={m.unlocked?'ops-badge unlocked':'ops-badge'} key={m.label}><strong>{m.unlocked?'✓':'○'}</strong><span>{m.label}</span><small>{m.target} approved</small></div>)}</div><p className="panel-note">Display only. Never bypasses QA or financial controls.</p></div>
  </section>

  <section className="panel credentials-panel"><span className="kicker">CREDENTIAL INVENTORY</span><h2>{credentials.bundles.filter(b=>b.status==='AVAILABLE').length} bundles available</h2><div className="credential-layout"><form className="credential-form" onSubmit={addCredential}><label>Campaign<select name="campaignSlug" required>{credentials.campaigns.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select></label><label>Bundle label<input name="label" required placeholder="SPAIN-0001"/></label><div className="grid2"><label>A username<input name="aUsername" required/></label><label>A password<input name="aPassword" type="password" required autoComplete="new-password"/></label><label>B username<input name="bUsername" required/></label><label>B password<input name="bPassword" type="password" required autoComplete="new-password"/></label></div><label>Pair-specific invitation code (optional)<input name="pairInvitationCode"/></label><label>Notes<input name="notes"/></label><button disabled={busy!==''}>{busy==='credential-create'?'Encrypting & saving…':'Add credential bundle'}</button><small>Passwords are encrypted before storage and never returned by inventory APIs.</small></form><div className="credential-list">{credentials.bundles.slice(0,12).map(b=><div key={b.id}><strong>{b.label}</strong><span>{b.status}</span><small>{b.accounts.sort((a,c)=>a.slot.localeCompare(c.slot)).map(a=>a.slot+': '+a.username).join(' · ')}</small></div>)}</div></div></section>
 </main>
}