'use client';
import {useEffect,useState} from 'react';
type Campaign={campaignKey:string;leads:number;customers:number;spendCents:number;cplCents:number|null;cacCents:number|null;conversionRate:number|null};
type Stats={leads:number;usLeads:number;spainLeads:number;customers:number;target:number;progress:number;totalSpendCents:number;cplCents:number|null;cacCents:number|null;leadConversionRate:number|null;totalClicks:number;totalImpressions:number;ctr:number|null;cpcCents:number|null;campaigns:Campaign[]};
const money=(c:number|null)=>c==null?'—':'$'+(c/100).toFixed(2);
export default function Admin(){
 const[s,setS]=useState<Stats|null>(null);
 useEffect(()=>{fetch('/api/admin/stats').then(r=>r.json()).then(setS)},[]);
 return <main className="admin"><div className="logo">PAIR<span>VOICE</span> <small>GROWTH</small></div><h1>20,000 Lead Mission</h1>{!s?<p>Loading…</p>:<><div className="meter"><i style={{width:`${Math.min(s.progress,100)}%`}}/></div><strong className="progress">{s.leads.toLocaleString()} / {s.target.toLocaleString()} <em>{s.progress}%</em></strong><div className="stats"><article><b>{s.leads.toLocaleString()}</b><span>Email leads</span></article><article><b>{money(s.cplCents)}</b><span>Cost per lead (CPL)</span></article><article><b>{money(s.cacCents)}</b><span>Customer acquisition cost (CAC)</span></article><article><b>{money(s.totalSpendCents)}</b><span>Total acquisition spend</span></article><article><b>{s.usLeads.toLocaleString()}</b><span>U.S. leads</span></article><article><b>{s.spainLeads.toLocaleString()}</b><span>Spain leads</span></article><article><b>{s.customers.toLocaleString()}</b><span>Converted customers</span></article><article><b>{s.leadConversionRate==null?'—':s.leadConversionRate+'%'}</b><span>Lead → customer</span></article><article><b>{s.ctr==null?'—':s.ctr+'%'}</b><span>Ad CTR</span></article><article><b>{money(s.cpcCents)}</b><span>Cost per click</span></article></div><h2>Campaign KPIs</h2><div className="stats">{s.campaigns.map(c=><article key={c.campaignKey}><strong>{c.campaignKey}</strong><span>{c.leads} leads · CPL {money(c.cplCents)} · CAC {money(c.cacCents)} · {c.conversionRate==null?'—':c.conversionRate+'%'} converted</span></article>)}</div></>}</main>
}
