'use client';
import { FormEvent,useEffect,useState } from 'react';

type Result={referralCode:string;inviteCode:string};
export default function Home(){
 const [result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[lang,setLang]=useState<'en'|'es'>('en'),[pairInvite,setPairInvite]=useState('');
 useEffect(()=>{const q=new URLSearchParams(location.search);setPairInvite(q.get('pair')||'');if(navigator.language.toLowerCase().startsWith('es'))setLang('es')},[]);
 const t=lang==='es'?{join:'Únete ahora',eyebrow:'OPORTUNIDADES DE VOZ PAGADAS • ESPAÑA',h1:'Tu voz',h2:'tiene valor.',lead:'Únete a PairVoice para proyectos pagados de grabación de voz. La oportunidad introductoria en España paga $50 en total por pareja aceptada.',cta:'Regístrate para trabajo de voz →',free:'Gratis • 18+',start:'Empieza con tu primera oportunidad.',profile:'Crea tu perfil gratis',done:'¡Ya estás en PairVoice!',next:'Invita a tu compañero para completar tu pareja.',invite:'Invitar por WhatsApp',partnerTitle:'Únete a esta pareja',partnerDone:'Pareja completada'}:{join:'Join now',eyebrow:'PAID VOICE OPPORTUNITIES • UNITED STATES',h1:'Your voice',h2:'has value.',lead:'Join PairVoice for paid voice-recording projects. Our introductory U.S. opportunity pays $60 total per accepted pair.',cta:'Sign up for voice work →',free:'Free to join • 18+',start:'Start with your first opportunity.',profile:'Create your free profile',done:"You're on PairVoice!",next:'Invite your recording partner to complete your pair.',invite:'Invite on WhatsApp',partnerTitle:'Join this PairVoice pair',partnerDone:'Pair completed'};
 async function signup(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const f=new FormData(e.currentTarget);const q=new URLSearchParams(location.search);const payload={firstName:f.get('firstName'),email:f.get('email'),phone:f.get('phone'),country:f.get('country'),language:f.get('language'),accent:f.get('accent'),is18Plus:f.get('age')==='on',consent:f.get('consent')==='on',ref:q.get('ref'),campaign:q.get('campaign')||q.get('utm_campaign')};const r=await fetch('/api/signup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();setLoading(false);if(!r.ok){setError(d.error||'Signup failed');return}setResult(d)}
 async function joinPair(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const f=new FormData(e.currentTarget);const payload={inviteCode:pairInvite,firstName:f.get('firstName'),email:f.get('email'),phone:f.get('phone'),country:f.get('country'),language:f.get('language'),accent:f.get('accent'),is18Plus:f.get('age')==='on',consent:f.get('consent')==='on'};const r=await fetch('/api/pair',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();setLoading(false);if(!r.ok){setError(d.error||'Unable to join pair');return}setResult({referralCode:d.referralCode,inviteCode:''})}
 const invite=result?.inviteCode?location.origin+'/?pair='+result.inviteCode:'';
 const formFields=<><div className="grid2"><label>First name<input required name="firstName"/></label><label>Phone / WhatsApp<input name="phone" type="tel"/></label></div><label>Email<input required type="email" name="email"/></label><div className="grid2"><label>Country<select required name="country" defaultValue=""><option value="" disabled>Select</option><option>United States</option><option>Spain</option></select></label><label>Primary language<select required name="language" defaultValue=""><option value="" disabled>Select</option><option>English</option><option>Spanish</option></select></label></div><label>Accent / dialect<input required name="accent" placeholder="e.g. American, Spain Spanish"/></label><label className="check"><input required name="age" type="checkbox"/><span>I confirm I am 18 or older.</span></label><label className="check"><input required name="consent" type="checkbox"/><span>I agree to be contacted about PairVoice opportunities.</span></label>{error&&<p className="error">{error}</p>}</>;
 return <main><nav><div className="logo">PAIR<span>VOICE</span></div><div className="navright"><button className="language" onClick={()=>setLang(lang==='en'?'es':'en')}>{lang==='en'?'ES':'EN'}</button><a href="#join">{t.join}</a></div></nav>
 <section className="hero"><div className="eyebrow">{t.eyebrow}</div><h1>{t.h1}<br/><em>{t.h2}</em></h1><p className="lead">{t.lead}</p><div className="actions"><a className="primary" href="#join">{t.cta}</a><span>{t.free}</span></div><div className="chips"><b>English</b><b>Español</b><b>US Accents</b><b>Spain Spanish</b></div></section>
 <section className="steps"><div><i>01</i><h3>Create your profile</h3><p>Language, accent and location. About 60 seconds.</p></div><div><i>02</i><h3>Invite your partner</h3><p>Pair projects require a second registered participant.</p></div><div><i>03</i><h3>Qualify & record</h3><p>Follow the requirements for each available project.</p></div><div><i>04</i><h3>Get paid</h3><p>Accepted work becomes eligible for payment under project terms.</p></div></section>
 <section className="join" id="join"><div><div className="eyebrow">PAIRVOICE COMMUNITY</div><h2>{pairInvite?t.partnerTitle:t.start}</h2><p>{pairInvite?'Complete your own registration and consent to join the participant who invited you.':'One profile can match you with current and future opportunities based on your language, accent and location.'}</p>{!pairInvite&&<div className="affiliate"><strong>Invite people. Earn referral rewards.</strong><br/>Eligible direct referrals can generate a small commission when their qualifying missions are completed and approved.</div>}</div><div className="card">{result?<div className="success"><div>✓</div><h3>{pairInvite?t.partnerDone:t.done}</h3>{!pairInvite&&result.inviteCode&&<><p>{t.next}</p><a className="share" href={'https://wa.me/?text='+encodeURIComponent('Join my PairVoice pair: '+invite)}>{t.invite}</a><button className="copy" onClick={()=>navigator.clipboard.writeText(invite)}>Copy partner link</button></>}<small>Your referral code: {result.referralCode}</small></div>:pairInvite?<form onSubmit={joinPair}><h3>{t.partnerTitle}</h3>{formFields}<button disabled={loading}>{loading?'Joining pair…':'Complete my registration →'}</button><small>Both participants must register separately and provide their own consent.</small></form>:<form onSubmit={signup}><h3>{t.profile}</h3>{formFields}<button disabled={loading}>{loading?'Creating profile…':'Create my PairVoice account →'}</button><small>No signup fee. Eligibility and compensation vary by project.</small></form>}</div></section><footer><div className="logo">PAIR<span>VOICE</span></div><p>Paid voices. Real people. Global opportunities.</p></footer></main>
}
