export const pairStates=['PARTNER_PENDING','PAIRED','READINESS_PENDING','READY','RECORDING','SUBMITTED','INTERNAL_QA','CLIENT_QA','REWORK_REQUIRED','APPROVED','PAYABLE','PAID','PAYMENT_FAILED','REJECTED','CANCELLED','ON_HOLD'] as const;
export type PairState=typeof pairStates[number];
export const allowedPairTransitions:Record<PairState,readonly PairState[]>={
 PARTNER_PENDING:['PAIRED','CANCELLED','ON_HOLD'],PAIRED:['READINESS_PENDING','CANCELLED','ON_HOLD'],
 READINESS_PENDING:['READY','CANCELLED','ON_HOLD'],READY:['RECORDING','CANCELLED','ON_HOLD'],
 RECORDING:['SUBMITTED','REWORK_REQUIRED','CANCELLED','ON_HOLD'],SUBMITTED:['INTERNAL_QA','ON_HOLD'],
 INTERNAL_QA:['CLIENT_QA','REWORK_REQUIRED','REJECTED','ON_HOLD'],CLIENT_QA:['APPROVED','REWORK_REQUIRED','REJECTED','ON_HOLD'],
 REWORK_REQUIRED:['RECORDING','SUBMITTED','CANCELLED','ON_HOLD'],APPROVED:['PAYABLE','ON_HOLD'],
 PAYABLE:['PAID','PAYMENT_FAILED','ON_HOLD'],PAYMENT_FAILED:['PAYABLE','PAID','ON_HOLD'],
 ON_HOLD:['PARTNER_PENDING','PAIRED','READINESS_PENDING','READY','RECORDING','SUBMITTED','INTERNAL_QA','CLIENT_QA','REWORK_REQUIRED','APPROVED','PAYABLE','CANCELLED'],
 PAID:[],REJECTED:[],CANCELLED:[]
};
export function canTransitionPair(from:PairState,to:PairState){return from===to||allowedPairTransitions[from].includes(to)}
export const stateProgress:Record<PairState,number>={PARTNER_PENDING:10,PAIRED:20,READINESS_PENDING:30,READY:40,RECORDING:55,SUBMITTED:65,INTERNAL_QA:72,CLIENT_QA:82,REWORK_REQUIRED:58,APPROVED:90,PAYABLE:95,PAID:100,PAYMENT_FAILED:95,REJECTED:0,CANCELLED:0,ON_HOLD:0};