export const workflowStates = [
  'APPLIED','SCREENING','MANUAL_REVIEW','QUALIFIED','PARTNER_PENDING','PAIRED','TRAINING',
  'FUNCROWD_SETUP','FUNCROWD_TEST','READY','RECORDING','SUBMITTED','EXTERNAL_QA_PENDING',
  'REWORK_REQUIRED','APPROVED','PAYMENT_DUE','PAID','WAITLISTED','REJECTED','ABANDONED',
  'CREDENTIAL_HOLD','PAYMENT_FAILED',
] as const

export type WorkflowState = typeof workflowStates[number]

export const allowedTransitions: Partial<Record<WorkflowState, readonly WorkflowState[]>> = {
  APPLIED:['SCREENING','REJECTED','ABANDONED'],
  SCREENING:['MANUAL_REVIEW','QUALIFIED','REJECTED','ABANDONED'],
  MANUAL_REVIEW:['QUALIFIED','REJECTED'],
  QUALIFIED:['PARTNER_PENDING','PAIRED'],
  PARTNER_PENDING:['PAIRED','ABANDONED'],
  PAIRED:['TRAINING'],
  TRAINING:['FUNCROWD_SETUP','ABANDONED'],
  FUNCROWD_SETUP:['FUNCROWD_TEST','CREDENTIAL_HOLD'],
  FUNCROWD_TEST:['READY','CREDENTIAL_HOLD'],
  READY:['RECORDING'],
  RECORDING:['SUBMITTED','ABANDONED'],
  SUBMITTED:['EXTERNAL_QA_PENDING'],
  EXTERNAL_QA_PENDING:['REWORK_REQUIRED','APPROVED','REJECTED'],
  REWORK_REQUIRED:['RECORDING','SUBMITTED'],
  APPROVED:['PAYMENT_DUE'],
  PAYMENT_DUE:['PAID','PAYMENT_FAILED'],
  PAYMENT_FAILED:['PAYMENT_DUE'],
}

export function canTransition(from:WorkflowState,to:WorkflowState){return allowedTransitions[from]?.includes(to) ?? false}
