-- PairVoice clean catalog extension
create type recording_mode as enum ('CONVERSATION','VOICE_RECORDING','OTHER');
create table job_families(id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,recording_mode recording_mode not null,requires_pair boolean not null default false,description text,active boolean not null default true,created_at timestamptz not null default now());
alter table campaigns add column job_family_id uuid references job_families(id) on delete restrict,add column locale text,add column accent_target text,add column participant_count integer not null default 2 check(participant_count>0),add column device_requirement text,add column provider text;
create table source_postings(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references campaigns(id) on delete cascade,platform text not null,external_job_id text not null,url text not null,title text not null,compensation_type text not null default 'UNKNOWN' check(compensation_type in('HOURLY','FIXED','UNKNOWN')),observed_rate_cents integer check(observed_rate_cents is null or observed_rate_cents>=0),observed_currency text not null default 'USD',status text not null default 'OBSERVED' check(status in('OBSERVED','OPEN','CLOSED','ARCHIVED')),first_observed_at date,created_at timestamptz not null default now(),unique(platform,external_job_id));
create table source_contract_observations(id uuid primary key default gen_random_uuid(),source_posting_id uuid not null references source_postings(id) on delete cascade,worker_display_name text,observed_hours numeric(8,2),hourly_rate_cents integer,observed_month date,created_at timestamptz not null default now());
create table campaign_access(campaign_id uuid primary key references campaigns(id) on delete cascade,provider text not null,invitation_code text,reveal_state text not null default 'READY' check(reveal_state in('PARTNER_PENDING','PAIRED','READY','IN_PROGRESS')),updated_at timestamptz not null default now());
alter table leads add column campaign_id uuid references campaigns(id) on delete set null,add column source_posting_id uuid references source_postings(id) on delete set null;
create index campaigns_family_idx on campaigns(job_family_id);create index source_postings_campaign_idx on source_postings(campaign_id);create index leads_opportunity_idx on leads(campaign_id);
alter table job_families enable row level security;alter table source_postings enable row level security;alter table source_contract_observations enable row level security;alter table campaign_access enable row level security;revoke all on job_families,source_postings,source_contract_observations,campaign_access from anon,authenticated;
insert into job_families(slug,name,recording_mode,requires_pair,description) values ('paired-conversation','Paired Conversation Recording','CONVERSATION',true,'Two eligible speakers complete a structured conversational recording project together.'),('mobile-voice-recording','Mobile Voice Recording','VOICE_RECORDING',false,'Individual mobile voice-recording project.');
update campaigns c set job_family_id=j.id,participant_count=2,provider='FUNCROWD' from job_families j where j.slug='paired-conversation' and c.slug in('es-spain-v1','us-english-v1');
update campaigns set locale='es-ES',accent_target='Spain Spanish' where slug='es-spain-v1';update campaigns set locale='en-US',accent_target='U.S. English' where slug='us-english-v1';
insert into campaign_access(campaign_id,provider,invitation_code,reveal_state) select c.id,coalesce(c.provider,'FUNCROWD'),cv.default_invitation_code,'READY' from campaigns c join campaign_versions cv on cv.campaign_id=c.id and cv.status='PUBLISHED' where c.slug='es-spain-v1' on conflict(campaign_id) do nothing;
create or replace function upsert_public_lead_v2(p_email text,p_market_code text,p_consent boolean,p_detected_locale text,p_detected_languages text[],p_source text,p_campaign_key text,p_campaign_slug text,p_source_external_id text,p_landing_path text,p_referrer text,p_fbclid text,p_gclid text,p_utm_source text,p_utm_medium text,p_utm_campaign text,p_utm_content text,p_utm_term text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_campaign uuid;v_posting uuid;v_result jsonb;begin if p_campaign_slug is not null then select id into v_campaign from campaigns where slug=p_campaign_slug and active=true;end if;if p_source_external_id is not null then select id into v_posting from source_postings where external_job_id=p_source_external_id and (v_campaign is null or campaign_id=v_campaign);end if;v_result:=upsert_public_lead(p_email,p_market_code,p_consent,p_detected_locale,p_detected_languages,p_source,p_campaign_key,p_landing_path,p_referrer,p_fbclid,p_gclid,p_utm_source,p_utm_medium,p_utm_campaign,p_utm_content,p_utm_term);update leads set campaign_id=coalesce(v_campaign,campaign_id),source_posting_id=coalesce(v_posting,source_posting_id) where email=lower(trim(p_email));return v_result;end $$;
grant execute on function upsert_public_lead_v2(text,text,boolean,text,text[],text,text,text,text,text,text,text,text,text,text,text,text,text) to anon,authenticated;
