'use client';
import {FormEvent,useEffect,useState} from 'react';
import {trackFunnelEvent} from '../../../lib/funnel';

export default function InvitePage({params}:{params:Promise<{code:string}>}){
 const[code,setCode]=useState(''),[lang,setLang]=useState<'en'|'es'>('en'),[done,setDone]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{params.then(p=>setCode(p.code.toUpperCase()));const q=new URLSearchParams(location.search),browser=navigator.language.toLowerCase();setLang(q.get('lang')==='es'||(!q.get('lang')&&browser.startsWith('es'))?'es':'en');trackFunnelEvent('invite_view');},[params]);
 const es=lang==='es';
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');trackFunnelEvent('partner_signup_started');const f=new FormData(e.currentTarget),r=await fetch('/api/lead',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({first_name:f.get('first_name'),email:f.get('email'),language:lang,market_code:(navigator.language.split('-')[1]||'UNKNOWN').toUpperCase(),detected_locale:navigator.language,detected_languages:navigator.languages,referral_code:code,landing_path:location.pathname,source:'partner_invite',marketing_campaign_key:'partner_invite',consent:f.get('consent')==='on'})}),d=await r.json();setLoading(false);if(!r.ok){setError(d.error||(es?'No se pudo completar el registro.':'Signup failed'));return}setDone(true);trackFunnelEvent('partner_signup_completed');trackFunnelEvent('email_queued');}
 return <main className="invitePage"><nav><div className="logo">PAIR<span>VOICE</span></div><button className="language" onClick={()=>setLang(es?'en':'es')}>{es?'EN':'ES'}</button></nav><section className="inviteWrap"><div className="eyebrow">{es?'INVITACIÓN DE PAREJA':'PARTNER INVITATION'}</div><h1>{es?'Únete a tu pareja.':'Join your partner.'}</h1><p className="lead">{es?'Tu compañero ya se registró en PairVoice. Regístrate para que podamos conectaros para oportunidades de voz pagadas.':'Your partner has already joined PairVoice. Sign up so we can connect you for paid voice opportunities.'}</p><div className="card">{done?<div className="success"><div>✓</div><h3>{es?'¡Tu pareja está conectada!':'Your pair is connected!'}</h3><p>{es?'Te enviaremos un correo con los próximos pasos.':'We’ll email you the next steps.'}</p></div>:<form onSubmit={submit}><h3>{es?'Completa tu registro':'Complete your signup'}</h3><label htmlFor="partner-first-name">{es?'Nombre':'First name'}</label><input id="partner-first-name" required name="first_name" autoComplete="given-name" autoCapitalize="words" enterKeyHint="next"/><label htmlFor="partner-email">{es?'Correo electrónico':'Email address'}</label><input id="partner-email" required type="email" name="email" autoComplete="email" inputMode="email" autoCapitalize="none" spellCheck={false} enterKeyHint="done"/><label className="check" htmlFor="partner-consent"><input id="partner-consent" required name="consent" type="checkbox"/><span>{es?'Quiero recibir oportunidades de PairVoice por correo.':'Send me PairVoice opportunities and updates by email.'}</span></label>{error&&<p className="error">{error}</p>}<button disabled={loading}>{loading?(es?'Guardando…':'Saving…'):(es?'Unirme a mi pareja →':'Join my partner →')}</button><small>{es?'Código de invitación: ':'Invitation code: '}{code}</small></form>}</div></section></main>;
}
